### PR TITLE
docs: fix readme link

### PR DESCRIPTION
**Pull request by vim-usds**
## PR Checklist

- [ ] Addresses an existing open issue: fixes #000
- [ ] That issue was marked as [accepting prs](https://github.com/JoshuaKGoldberg/linting-typescript-in-2023/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [ ] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/linting-typescript-in-2023/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Typo in the repo's README as to the link of the demo repo. Added the "https://" to the beginning of the link :)

PS: I might open it in a new tab as well! 

Thanks for the article on setting up prettier and eslint!

### CODE REVIEW

**Review by JoshuaKGoldberg — APPROVED** [review]
😍 thank you!

**Comment by JoshuaKGoldberg** [comment]
...we can ignore the build failures 😂 I'll fix these separately.

**Comment by vim-usds** [comment]
> ...we can ignore the build failures 😂 I'll fix these separately.

ohh I totally missed these! Thanks!

**Comment by JoshuaKGoldberg** [comment]
they were all my fault from mix and matching Yarn and pnpm, heh

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @vim-usds for docs

**Pull request merged**
